from dev.data.dataset import FoodDataset
from dev.data.dataloader import FoodDataLoader
from torch.utils.data import DataLoader
import torch

# Test code generated by Claude.
##### K-Fold tests #####

K = 5  # number of folds used across all tests


def _make_dataloader(k: int = K, shuffle: bool = False) -> tuple[FoodDataset, FoodDataLoader]:
    """Helper: return a (dataset, dataloader) pair ready for k-fold tests."""
    dataset = FoodDataset()
    dataloader = FoodDataLoader(dataset, batch_size=4, shuffle=shuffle, k=k)
    return dataset, dataloader


def test_kfold_correct_number_of_folds():
    """get_kfold_dataloaders should yield exactly k (fold, train_loader, val_loader) tuples."""
    _, dataloader = _make_dataloader()
    folds = list(dataloader.get_k_fold_dataloaders())
    assert len(folds) == K, f"Expected {K} folds, got {len(folds)}"


def test_kfold_fold_indices_are_sequential():
    """Fold numbers should be 0, 1, 2, ... k-1 in order."""
    _, dataloader = _make_dataloader()
    fold_numbers = [fold for fold, _, _ in dataloader.get_k_fold_dataloaders()]
    assert fold_numbers == list(range(K)), f"Expected fold indices {list(range(K))}, got {fold_numbers}"


def test_kfold_returns_dataloaders():
    """Each iteration should yield a torch DataLoader for both train and val."""
    _, dataloader = _make_dataloader()
    for fold, train_loader, val_loader in dataloader.get_k_fold_dataloaders():
        assert isinstance(train_loader, DataLoader), f"Fold {fold}: train_loader is not a DataLoader"
        assert isinstance(val_loader, DataLoader), f"Fold {fold}: val_loader is not a DataLoader"


def test_kfold_batches_are_tensors():
    """Batches from both train and val loaders should be torch Tensors."""
    _, dataloader = _make_dataloader()
    for fold, train_loader, val_loader in dataloader.get_k_fold_dataloaders():
        for images, labels in train_loader:
            assert isinstance(images, torch.Tensor), f"Fold {fold}: train images are not a Tensor"
            assert isinstance(labels, torch.Tensor), f"Fold {fold}: train labels are not a Tensor"
            break
        for images, labels in val_loader:
            assert isinstance(images, torch.Tensor), f"Fold {fold}: val images are not a Tensor"
            assert isinstance(labels, torch.Tensor), f"Fold {fold}: val labels are not a Tensor"
            break


def test_kfold_no_overlap_between_train_and_val():
    """Train and val indices must be fully disjoint within every fold."""
    dataset, dataloader = _make_dataloader()
    all_indices = set(range(len(dataset)))

    for fold, train_loader, val_loader in dataloader.get_k_fold_dataloaders():
        # Reconstruct the index sets from the underlying datasets
        train_indices = set(train_loader.dataset.indices)
        val_indices   = set(val_loader.dataset.indices)

        overlap = train_indices & val_indices
        assert len(overlap) == 0, (
            f"Fold {fold}: {len(overlap)} indices appear in both train and val: {overlap}"
        )


def test_kfold_union_covers_full_dataset():
    """The union of train and val indices across a single fold should equal the full dataset."""
    dataset, dataloader = _make_dataloader()
    all_indices = set(range(len(dataset)))

    for fold, train_loader, val_loader in dataloader.get_k_fold_dataloaders():
        train_indices = set(train_loader.dataset.indices)
        val_indices   = set(val_loader.dataset.indices)

        union = train_indices | val_indices
        assert union == all_indices, (
            f"Fold {fold}: union of train+val indices does not cover the full dataset. "
            f"Missing: {all_indices - union}"
        )


def test_kfold_val_size_is_approximately_one_kth():
    """Each val fold should contain roughly 1/k of the total samples (within ±1 for uneven splits)."""
    dataset, dataloader = _make_dataloader()
    n = len(dataset)
    expected_val_size = n // K

    for fold, _, val_loader in dataloader.get_k_fold_dataloaders():
        actual_val_size = len(val_loader.dataset)
        assert abs(actual_val_size - expected_val_size) <= 1, (
            f"Fold {fold}: val size {actual_val_size} deviates from expected ~{expected_val_size}"
        )


def test_kfold_val_sets_are_mutually_exclusive_across_folds():
    """The val set of each fold should not overlap with the val set of any other fold."""
    dataset, dataloader = _make_dataloader()
    val_index_sets = []

    for fold, _, val_loader in dataloader.get_k_fold_dataloaders():
        val_index_sets.append((fold, set(val_loader.dataset.indices)))

    for i, (fold_i, indices_i) in enumerate(val_index_sets):
        for fold_j, indices_j in val_index_sets[i + 1:]:
            overlap = indices_i & indices_j
            assert len(overlap) == 0, (
                f"Val sets of fold {fold_i} and fold {fold_j} overlap on {len(overlap)} indices: {overlap}"
            )


def test_kfold_val_sets_union_covers_full_dataset():
    """The union of all k val sets should cover the entire dataset exactly once."""
    dataset, dataloader = _make_dataloader()
    all_indices = set(range(len(dataset)))
    all_val_indices = []

    for _, _, val_loader in dataloader.get_k_fold_dataloaders():
        all_val_indices.extend(val_loader.dataset.indices)

    assert set(all_val_indices) == all_indices, "Union of all val sets does not equal the full dataset"
    assert len(all_val_indices) == len(dataset), (
        f"Total val indices ({len(all_val_indices)}) != dataset size ({len(dataset)}): "
        "some indices appear in more than one val fold"
    )