# K=3, augment_fraction = 0.5 Configuration for this model. Based on configuration file used in
# previous MLOps project. Adjusted for this project.

experiment_name: "project_nn_k9_aug05"
seed: 42

data:
  #dataset_type: "tcga"
  data_path: "data/dataset_split"
  labels_path: "data/train_labels.csv"
  image_dir: "data/train_set/train_set/train_set/"
  shuffle: true
  image_shape: [224, 224]
  batch_size: 64
  classes: 80
    
  val_fraction: 0.2
  augment_fraction: 0.5 # fraction of images in the training set that should be augmented per epoch
  augmentation_function: "rotate_translate_flip" # function name to be used as in dev/data/transformations.py
  k: 9 # Number of folds for k-fold cross-validation. 1 for simple train-val split

model:
  dropout_rate: 0.25
  use_class_weights: true

training:
  epochs: 100
  learning_rate: 0.001
  save_dir: "./experiments/k9_aug05_config/"
  log_dir: "runs/k9_aug05_config/"
  granularity: 100
  num_workers: 8
  weight_decay: 0.0001
  early_stopping_patience: 20

  # TODO: Implement step on plateau scheduler
  scheduler:
    step_size: 5
    gamma: 0.5