# Standard Configuration for this model. Based on configuration file used in
# previous MLOps project. Adjusted for this project.

experiment_name: "project_nn_standard"
seed: 42

data:
  #dataset_type: "tcga"
  data_path: "data/dataset_split"
  labels_path: "data/train_labels.csv"
  image_dir: "data/train_set/train_set/train_set/"
  shuffle: true
  image_shape: [224, 224]
  batch_size: 64
  classes: 80
    
  val_fraction: 0.2
  augment_fraction: 0.5 # fraction of images in the training set that should be augmented per epoch
  augmentation_function: "rotate_translate_flip" # function name to be used as in dev/data/transformations.py
  k: 4 # Number of folds for k-fold cross-validation 

model:

  dropout_rate: 0.25
  use_class_weights: true

training:
  epochs: 30
  learning_rate: 0.001
  save_dir: "./experiments/standard_config/"
  log_dir: "runs/"
  num_workers: 0
  granularity: 100
  weight_decay: 0.0001

  # TODO: Implement step on plateau scheduler
  scheduler:
    step_size: 5
    gamma: 0.5