# Standard Configuration for this model. Based on configuration file used in
# previous MLOps project. Adjusted for this project.

experiment_name: "tcga_champion"
seed: 42

data:
  #dataset_type: "tcga"
  data_path: "data/dataset_split"
  labels_path: "data/train_labels.csv"
  image_dir: "data/train_set/train_set/train_set/"
  shuffle: true
  input_shape: [3, 96, 96]
  batch_size: 64
  num_workers: 0
  val_fraction: 0.2
  test_fraction: 0.1
  aggregation_method: "mean"
  k: 4 # Number of folds for k-fold cross-validation 

model:
  #type: "late_fusion"

  # Multi-modal dimensions
  #visual_dim: 768   # TITAN embeddings dimension
  
  hidden_dims: [1024, 512, 256, 128]`
  dropout_rate: 0.25

  use_batch_norm: true
  # Activation function
  # Possible options for this implementation are:
  # - "relu"
  # - "gelu"
  activation: "gelu"

  # Loss function
  # Possible options for this implementation are:
  # - "CrossEntropyLoss"
  criterion: "CrossEntropyLoss"
  use_class_weights: true

training:
  epochs: 10
  learning_rate: 0.0005
  save_dir: "./experiments/standard_config"
  granularity: 100
  weight_decay: 0.015

  # TODO: Implement step on plateau scheduler
  scheduler:
    step_size: 25
    gamma: 0.5