# Test. Uses smaller image size and 1 epoch for code testing purposes only.. Configuration for this model. Based on configuration file used in
# previous MLOps project. Adjusted for this project.

experiment_name: "project_nn_test"
seed: 42

data:
  #dataset_type: "tcga"
  data_path: "data/dataset_split"
  labels_path: "data/train_labels.csv"
  image_dir: "data/train_set/train_set/train_set/"
  shuffle: true
  image_shape: [224, 224]
  batch_size: 64
  num_workers: 0
  classes: 80
    
  val_fraction: 0.2
  augment_fraction: 0.5 # fraction of images in the training set that should be augmented per epoch
  augmentation_function: "rotate_translate_flip" # function name to be used as in dev/data/transformations.py
  k: 1 # Number of folds for k-fold cross-validation 

model:
  #type: "late_fusion"

  # Multi-modal dimensions
  #visual_dim: 768   # TITAN embeddings dimension

  dropout_rate: 0.25

  use_batch_norm: true
  # Activation function
  # Possible options for this implementation are:
  # - "relu"
  # - "gelu"
  activation: "gelu"

  # Loss function
  # Possible options for this implementation are:
  # - "CrossEntropyLoss"
  criterion: "CrossEntropyLoss"
  use_class_weights: true

training:
  epochs: 3
  learning_rate: 0.001
  save_dir: "./experiments/test_config/"
  granularity: 100
  weight_decay: 0.0001

  # TODO: Implement step on plateau scheduler
  scheduler:
    step_size: 2
    gamma: 0.5